### ISSUE TITLE
cluster scrape result not sent if single subressource could not be processed

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma-metrics-collector#122]
**Description**

KMC must send partial data even if processing a single resource fails:

for example: 
- redis parsing fails
- number of nodes and pvcs could be listed

expected result: 
- any data which was able to get parsed should be send to the target system
- for failing data scrapes, the old values should be used
- for failing data scrapes, alerts shoul get triggered

**Comment by a-thaler** [comment]
A proposal on how to refactor the caching logic is done at https://github.com/kyma-project/kyma-metrics-collector/pull/123
